### ISSUE TITLE
Ticket does not concatenate to redirect URL correctly

### ISSUE THREAD

**Issue by tithanayut** [remove158/chula-sso#1]
When a redirect URL with query params is passed to the SSO service, a ticket must be concatenated to the redirect URL in the way that the validity of query params is conserved.

For example, a successful authentication on `http://sso.com/login?service=http://example.com/?redirect=/home` must redirect the user to `http://example.com/?redirect=/home&ticket=...` instead of ` http://example.com/?redirect=/home?ticket=...`. Notice the difference in the use of `?` and `&` before ticket param.

**Comment by remove158** [comment]
Thanks for the report.
Fixed in #2 
New released: https://github.com/remove158/chula-sso/releases/tag/v1.1.0
